.circleci/config.yml
circle.yml

[NABI-7] configured yml file

---

package-lock.json
package.json
src/ts/index.tsx
src/ts/main/components/AppContainer.tsx
src/ts/main/components/Homepage.tsx
src/ts/main/test/AppContainer.test.tsx

[NABI-4] react router

---

src/ts/main/test/AppContainer.test.tsx
src/ts/main/test/__snapshots__/AppContainer.test.tsx.snap

- Refactored AppContainer uni tests

[NABI-8] improved AppContainer test

---

src/ts/ProfileBuilder/components/ProfileBuilder.tsx
src/ts/ProfileBuilder/index.ts
src/ts/Registration/components/Registration.tsx
src/ts/Registration/test/Registration.test.tsx
src/ts/Registration/test/__snapshots__/Registration.test.tsx.snap
src/ts/main/components/AppContainer.tsx

- Added ProfileBuilder and set up boilerplates
- Added redirect functionality on submission of Registration form
- Added unit test

[NABI-9] profile builder

---

README.md

- Improved description and instructions in readme file

[CDN-13] readme file

---

src/ts/Registration/components/Registration.tsx

- added role to be set to 'instructor' in redirect conditional

[NABI-11] added role in redirect conditional

---

src/ts/Registration/components/RegistrationForm.tsx
src/ts/Registration/model.ts
tsconfig.json

- Added type for HearAboutUs
- Added object variable hearAboutUsInfo
- Return MenuItem based on hearAboutUsInfo object

[NABI-10] types hear about us

---

src/ts/ProfileBuilder/components/BasicInfo/BasicInfo.tsx
src/ts/ProfileBuilder/components/ProfileBuilder.tsx

- Added BasicInfo directory
- Added BasicInfo component
- Integrated BasicInfo component with ProfileBuilder

[NABI-25] added BasicInfo and integrated it with ProfileBuilder

---

src/ts/ProfileBuilder/components/ProfileBuilder.tsx
src/ts/ProfileBuilder/test/__snapshots__/ProfileBuilder.unit.test.tsx.snap

- fixed stepper styles on mobile

[NABI-27] removed padding in stepper in mobile

---

src/ts/ProfileBuilder/test/BasicInfo.unit.test.tsx
src/ts/ProfileBuilder/test/__snapshots__/BasicInfo.unit.test.tsx.snap

- Added test file for BasicInfo
- Wrote unit tests for BasicInfo

[NABI-26] added unit tests for BasicInfo

---

src/ts/ProfileBuilder/components/BasicInfo/BasicInfo.tsx
src/ts/ProfileBuilder/components/BasicInfo/NameLocationBio.tsx
src/ts/ProfileBuilder/components/ProfileBuilder.tsx
src/ts/ProfileBuilder/test/NameLocationBio.unit.test.tsx
src/ts/ProfileBuilder/test/__snapshots__/NameLocationBio.unit.test.tsx.snap
src/ts/Registration/components/RegistrationForm.tsx
src/ts/index.tsx

- Renamed NameAndLocation to NameLocationBio
- Renamed NameAndLocation test file and all instances of NameAndLocation
- Added bio textfield to NameLocationBio
- Added styles

[NABI-30] Bio

---

public/index.html

- Changed HTML document title from "React App" to "Nabi Music"
- deleted unnecessary comments

[NABI-33] changed page title

---

src/assets/css/index.css
src/ts/Instructors/ProfileBuilder/components/BasicInfo/NameLocationBio/NameLocationBio.tsx
src/ts/Instructors/ProfileBuilder/test/__snapshots__/NameLocationBio.unit.test.tsx.snap
src/ts/Users/Registration/components/RegistrationForm.tsx
src/ts/index.tsx

Implements [[NABI-60]](https://iamvane.backlog.com/view/NABI-60)
- Eliminate margin from User's displayName
- Fix radio buttons selected color
- Fix styles for active step
- Fix styles for stepper description going off the white space on medium/small screens
- Fixed border radio of EditName modal

[NABI-60] style fixes

---

src/ts/Users/actions.ts
src/ts/Users/constants/ActionTypes.ts
src/ts/Users/reducer.ts
src/ts/Users/test/Users-actions.test.ts
src/ts/Users/test/Users-reducer.test.ts
src/ts/index.tsx

Implements [[NABI-62]](https://iamvane.backlog.com/view/NABI-62)
**Main Tasks**
- styled buttons 
- renamed action types enum

[NABI-62] styled buttons and renamed Registration constant to User

---

src/assets/css/index.css
src/ts/Instructors/components/ProfileBuilder.tsx
src/ts/Users/components/Registration.tsx
src/ts/Users/test/__snapshots__/Registration.unit.test.tsx.snap
src/ts/main/components/Homepage.tsx
src/ts/main/components/PageTitle.tsx
src/ts/main/index.ts
src/ts/main/test/PageTitle.unit.test.tsx
src/ts/main/test/__snapshots__/PageTitle.unit.test.tsx.snap

Implements [[NABI-83]](https://iamvane.backlog.com/view/NABI-83)
**Main Tasks**
- Add component for page title
- Integrate component in current pages
- Add unit tests for PageTitle component
- Update existing snapshots
- Did some minor refactoring

[NABI-83] page title

---

src/assets/css/index.css
src/ts/Instructors/components/BasicInfo/BasicInfo.tsx
src/ts/Instructors/components/BasicInfo/Rates.tsx
src/ts/Instructors/test/Rates.unit.test.tsx
src/ts/Instructors/test/__snapshots__/BasicInfo.unit.test.tsx.snap
src/ts/Instructors/test/__snapshots__/Rates.unit.test.tsx.snap
src/ts/index.tsx

Implements [[NABI-87]](https://iamvane.backlog.com/view/NABI-87)
**Main Tasks:**
- Add rates fields
- Integrate rate fields with BasicInfo
- Add styles
- Unit tests
**TODO:** Refactor Rates code. make it DRYer.

[NABI-87] rates fields

---

src/ts/Instructors/components/BasicInfo/BasicInfo.tsx
src/ts/Instructors/components/BasicInfo/Rates.tsx
src/ts/Instructors/model.ts
src/ts/Instructors/test/BasicInfo.unit.test.tsx
src/ts/Instructors/test/NameLocationBio.unit.test.tsx
src/ts/Instructors/test/Rates.unit.test.tsx
src/ts/Instructors/test/__snapshots__/BasicInfo.unit.test.tsx.snap
src/ts/Instructors/test/__snapshots__/Rates.unit.test.tsx.snap

Implements: [[NABI-92]](https://iamvane.backlog.com/view/NABI-92)
**Main Tasks**
- Add rates state to BasicInfo
- Added rates props to Rates
- Added updateRates method to BasicInfo
- Added updateRates props to Rates
- Set rates textfield type to number
- Add edit unit tests as necessary

[NABI-92] rates state

---

src/ts/Instructors/components/BasicInfo/BasicInfo.tsx
src/ts/Instructors/components/BasicInfo/PlaceForLessons.tsx
src/ts/Instructors/model.ts
src/ts/Instructors/test/PlaceForLessons.unit.test.tsx
src/ts/Instructors/test/__snapshots__/BasicInfo.unit.test.tsx.snap
src/ts/Instructors/test/__snapshots__/PlaceForLessons.unit.test.tsx.snap

Implements [[NABI-99]](https://iamvane.backlog.com/view/NABI-99)
**Main Tasks**
- Added types/model for place for lessons
- Added checkbox fields for place for lessons
- Added place for lessons component
- Added input field for instructor studio
- Added styles
- Add/edit unit tests as necessary

Nabi 99 place for lessons fields

---

src/ts/Instructors/components/BasicInfo/BasicInfo.tsx
src/ts/Instructors/components/BasicInfo/PlaceForLessons.tsx
src/ts/Instructors/model.ts
src/ts/Instructors/test/BasicInfo.unit.test.tsx
src/ts/Instructors/test/PlaceForLessons.unit.test.tsx
src/ts/Instructors/test/__snapshots__/BasicInfo.unit.test.tsx.snap
src/ts/Instructors/test/__snapshots__/PlaceForLessons.unit.test.tsx.snap

Implements [[NABI-105]](https://iamvane.backlog.com/view/NABI-105)
**Main tasks:**
- Add placeforlessons state to BasicInfo
- Add placeforlessons props to PlaceForLessons components
- Added `handleChangePlaceForLessons` method to BasicInfo
- Added `updateStudioAddress` method to BasicInfo
- Update state on user selection
- Add edit unit tests as necessary

[NABI-105] place for lessons state

---

src/assets/css/index.css
src/ts/Instructors/components/BasicInfo/Availability.tsx
src/ts/Instructors/components/BasicInfo/BasicInfo.tsx
src/ts/Instructors/components/BasicInfo/NameLocationBio/NameLocationBio.tsx
src/ts/Instructors/components/BasicInfo/Rates.tsx
src/ts/Instructors/test/Availability.unit.test.tsx
src/ts/Instructors/test/__snapshots__/Availability.unit.test.tsx.snap
src/ts/Instructors/test/__snapshots__/BasicInfo.unit.test.tsx.snap
src/ts/Users/test/Registration.unit.test.tsx
src/ts/index.tsx

Implements [[NABI-109]](https://iamvane.backlog.com/view/NABI-109)
**Main Tasks**:
- Copy previously built availability component
- Style
- Add unit tests
**NOTE:** Unit tests needs improvement and component code needs refactoring. See https://iamvane.backlog.com/view/NABI-156

[NABI-109] availability

---

README.md

* Updated contributors in README.md file

[NO-TICKET] updated contributors

---

src/assets/css/index.css
src/ts/main/components/Drawer.tsx
src/ts/main/components/Header.tsx
src/ts/main/test/Drawer.unit.test.tsx
src/ts/main/test/__snapshots__/Drawer.unit.test.tsx.snap
src/ts/main/test/__snapshots__/Header.unit.test.tsx.snap

Implements [NABI-65](https://iamvane.backlog.com/view/NABI-65)
**Main task:**
- Set up drawer in the header
- Add drawer button to header
- When user clicks on the button a drawer displays

[NABI-65] menu drawer and  buttons

---

src/assets/css/index.css
src/ts/Instructors/actions.ts
src/ts/Instructors/components/BasicInfo/Availability.tsx
src/ts/Instructors/components/BasicInfo/BasicInfo.tsx
src/ts/Instructors/components/BasicInfo/Rates.tsx
src/ts/Instructors/components/Education/Education.tsx
src/ts/Instructors/components/Education/EducationAdded.tsx
src/ts/Instructors/components/Education/EducationFields.tsx
src/ts/Instructors/components/ProfileBuilder.tsx
src/ts/Instructors/model.ts
src/ts/Instructors/reducer.ts
src/ts/Instructors/test/Education.unit.test.tsx
src/ts/Instructors/test/EducationFields.unit.test.tsx
src/ts/Instructors/test/Instructors-actions.test.ts
src/ts/Instructors/test/Instructors-reducer.test.ts
src/ts/Instructors/test/__snapshots__/Education.unit.test.tsx.snap
src/ts/Instructors/test/__snapshots__/EducationFields.unit.test.tsx.snap
src/ts/Users/components/Registration.tsx
src/ts/Users/test/Registration.unit.test.tsx
src/ts/main/components/AppContainer.tsx
src/ts/main/components/PageTitle.tsx

Implements [[NABI-141]](https://iamvane.backlog.com/view/NABI-141)
**Main Tasks:**
- Add state array to class component
- Update InstructorState model
- Make instructorUpdate on add
- Add SelectedEducation component (includes trash icon)
- Map education state to render SelectedEducation component
- Add/edit unit tests as necessary

[NABI-141] education state

---

src/assets/css/index.css
src/ts/Users/components/AgeDisclaimer.tsx
src/ts/Users/components/BirthdayField.tsx
src/ts/Users/components/Registration.tsx
src/ts/Users/components/RegistrationForm.tsx
src/ts/Users/model.ts
src/ts/Users/test/AgeDisclaimer.unit.test.tsx
src/ts/Users/test/BirthdayField.unit.test.tsx
src/ts/Users/test/RegistrationForm.unit.test.tsx
src/ts/Users/test/__snapshots__/AgeDisclaimer.unit.test.tsx.snap
src/ts/Users/test/__snapshots__/Registration.unit.test.tsx.snap
src/ts/Users/test/__snapshots__/RegistrationForm.unit.test.tsx.snap
tsconfig.json
tslint.json

Originally https://github.com/iamvane/nabi_ui/pull/45

[NABI-25] birthday and dialog

---

src/assets/css/index.css
src/ts/Instructors/components/ProfileBuilder.tsx
src/ts/Users/components/RegistrationForm.tsx
src/ts/Users/test/__snapshots__/RegistrationForm.unit.test.tsx.snap
src/ts/index.tsx
src/ts/main/components/Welcome.tsx

[NO-TICKET] fixed styles

---

src/assets/css/index.css
src/ts/Instructors/components/ProfileBuilder/BasicInfo/BasicInfo.tsx
src/ts/Instructors/components/ProfileBuilder/BasicInfo/PlaceForLessons.tsx
src/ts/Instructors/components/ProfileBuilder/Education/Education.tsx
src/ts/Instructors/components/ProfileBuilder/Experience/Experience.tsx
src/ts/Instructors/components/ProfileBuilder/ProfileBuilder.tsx
src/ts/Instructors/components/ProfileBuilder/Qualifications/Qualifications.tsx
src/ts/Instructors/components/ProfileBuilder/Qualifications/QualificationsFields.tsx
src/ts/Instructors/model.ts
src/ts/Instructors/test/Education.unit.test.tsx
src/ts/Instructors/test/Qualifications.unit.test.tsx
src/ts/Instructors/test/QualificationsFields.unit.test.tsx
src/ts/Instructors/test/__snapshots__/Qualifications.unit.test.tsx.snap
src/ts/Instructors/test/__snapshots__/QualificationsFields.unit.test.tsx.snap
src/ts/main/components/Header.tsx
src/ts/main/test/__snapshots__/Header.unit.test.tsx.snap

Implements [NABI-195](https://iamvane.backlog.com/view/NABI-195)
* Added Qualification to the Profile Builder. Added necessary unit tests. Improved styles.

[NABI-195] qualifications

---

src/assets/css/index.css
src/assets/data/popularInstruments.ts
src/ts/index.tsx
src/ts/main/components/Homepage/InstrumentCard.tsx
src/ts/main/components/Homepage/PopularInstruments.tsx
src/ts/main/test/__snapshots__/Homepage.unit.test.tsx.snap
src/ts/main/test/__snapshots__/PopularInstrument.unit.test.tsx.snap

Implements [NABI-202](https://iamvane.backlog.com/view/NABI-202)
Added three columns of instruments on desktop including css animation.

[NABI-202] fixed popular instruments on large devices

---

src/ts/Users/components/Registration.tsx
src/ts/main/components/AppContainer.tsx
src/ts/main/components/Homepage/Banner.tsx
src/ts/main/components/Homepage/FreeLesson.tsx
src/ts/main/components/Homepage/InstrumentCard.tsx
src/ts/main/test/__snapshots__/Banner.unit.test.tsx.snap
src/ts/main/test/__snapshots__/FreeLesson.unit.test.tsx.snap

Implements [NABI-152](https://iamvane.backlog.com/view/NABI-152)
Added links to homepage

[NABI-152] add links

---

src/ts/index.tsx
src/ts/main/components/Drawer.tsx
src/ts/main/model.ts
src/ts/main/test/__snapshots__/Drawer.unit.test.tsx.snap

Implements [NABI-71](https://iamvane.backlog.com/view/NABI-71)
Added items to non-registered-users menu

[NABI-71] added items to non-registered menu

---

src/ts/Users/components/Registration.tsx
src/ts/Users/test/Registration.unit.test.tsx
src/ts/Users/test/__snapshots__/Registration.unit.test.tsx.snap

[NO-TICKET] fixed age disclaimer

---

src/ts/main/components/Homepage/InstrumentCard.tsx
src/ts/main/test/InstrumentCard.unit.test.tsx

[NO-TICKET] minor edits

---

src/ts/Users/components/Registration.tsx
src/ts/main/components/AppContainer.tsx

[NABI-214](https://iamvane.backlog.com/view/NABI-214)
**Main task** 
- Add conditionals for role = parent and for role = student
- Add routes (route path is welcome-students) and pass props via routes (actionText, welcomeText are in the design the actionUrl = "request-instructor") and render Welcome component

[NABI-214] welcome-page-for-student/parent
